### PR TITLE
Update tyk_analytics.with_mongo_and_gateway.conf

### PR DESCRIPTION
**Pull request by sedkis**

### CODE REVIEW

**Comment by buger** [comment]
Can you add more context to it?

**Comment by sedkis** [comment]
```
tyk_dashboard    | time="Apr 10 20:41:38" level=info msg="Sending config request for node: 3ecf3a5e-59f3-4339-7675-2002a5b7ba29-4fc27456919c" 
tyk_dashboard    | time="Apr 10 20:41:38" level=info msg="Got configuration for nodeID: 3ecf3a5e-59f3-4339-7675-2002a5b7ba29|4fc27456919c" 
tyk_dashboard    | Creating New Organisation
tyk_dashboard    | time="Apr 10 20:41:55" level=error msg="Couldn't create organisation: Post http://dashboard.tyk.docker:3000/admin/organisations: dial tcp: lookup dashboard.tyk.docker on 127.0.0.11:53: no such host" 
```
end user running into this error with the bootstrap GUI.  
I know @furkansenharputlu made changes though?

image

**Comment by furkansenharputlu** [comment]
I raised 2 PRs for this:
- https://github.com/TykTechnologies/tyk-analytics/pull/1759
hardcodes `localhost` in code.

- https://github.com/TykTechnologies/tyk-analytics/pull/1795
implements internal request to org&user creation APIs.

@buger prefers the second one, so when we merge it, I expect the problem will be solved without needing this change.

**Comment by buger** [comment]
@furkansenharputlu but does the @sedkis change fix the issue, even if temporary?

**Comment by furkansenharputlu** [comment]
@buger yes it was fixing when I tried.

**Pull request merged**
